[package]
name = "flyline"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
daemonize = "0.5.0"
ratatui = { git = "https://github.com/Marlinski/ratatui.git", rev = "fd8e0f024847af467129e0a166390d7e291c1b2e", features = ["default"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.31"
simplelog = "0.12"
log = "0.4"
ansi-to-tui = { git = "https://github.com/bozenalabs/ansi-to-tui.git", rev = "9101076f8e23010515ff6fe1571bf87a2d0d4abc"}
# ansi-to-tui = {path = "../ansi-to-tui" }
libc = "0.2.177"
bash-builtins = "0.4.1"
timeago = "0.5.0"
unicode-width = "0.2.0"
flash = "0.0.6"
anyhow = "1.0.100"
unicode-segmentation = "1.12.0"
itertools = "0.14.0"
glob = "0.3.3"
color-eyre = "0.6.5"
tree-sitter = "0.26.3"
tree-sitter-bash = "0.25.1"
fuzzy-matcher = "0.3.7"

[dependencies.crossterm]
# path = "../crossterm"
version = "0.29.0"
features = ["event-stream"]

[dependencies.tokio]
version = "1.47.1"
features = ["rt-multi-thread", "io-util", "sync", "full", "net", "signal", "rt", "process", "time", "io-std", "parking_lot", "macros"]
default-features = false

[dev-dependencies]
tempfile = "3.24.0"
testcontainers = {version = "0.26.3", features = ["blocking"] }

