[package]
name = "jobu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
daemonize = "0.5.0"
ratatui = {version = "0.29.0", features = ["default", "unstable-rendered-line-info"]}
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.31"
simple-logging = "2.0.2"
log = "0.4"
tui-textarea = "0.7.0"
ansi-to-tui = "7.0.0"
libc = "0.2.177"
bash-builtins = "0.4.1"
timeago = "0.5.0"
unicode-width = "0.2.0"
flash = "0.0.6"
anyhow = "1.0.100"
unicode-segmentation = "1.12.0"

[dependencies.crossterm]
version = "0.29.0"
features = ["event-stream"]

[dependencies.tokio]
version = "1.47.1"
features = ["rt-multi-thread", "io-util", "sync", "full", "net", "signal", "rt", "process", "time", "io-std", "parking_lot", "macros"]
default-features = false
