name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-ubuntu-1604:
    name: Build and test on Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          # load: true # Storing the image in docker is slow, so try and rely on caching
          file: docker/release_builder.Dockerfile
          target: flyline-extracted-library
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=${{ runner.temp }}/flyline-build

      - name: Run tests
        # running the tests by building an image is a cache friendly way to do it
        # if we build a container, the previous step would need to have exported the image to docker
        # which is slow
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/release_builder.Dockerfile
          target: flyline-tests
          cache-from: type=gha
          # cache-to: type=gha,mode=max
      
      - name: Save built library artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-flyline-library
          path: ${{ runner.temp }}/flyline-build/libflyline.so

  bash-integration-tests:
    name: Test bashn${{ matrix.bash_version }} using built library
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bash_version: [ "4.4-rc1", "4.4.18", "5.0", "5.1.16", "5.2", "5.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built library artifact
        uses: actions/download-artifact@v4
        with:
          name: built-flyline-library
          path: ${{ runner.temp }}/flyline-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run integration tests
        uses: docker/build-push-action@v6
        with:
          context: ${{ runner.temp }}/flyline-build
          file: docker/bash_integration_test.Dockerfile
          build-args: BASH_VERSION=${{ matrix.bash_version }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
