name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-ubuntu-1604:
    name: Build and test on Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          # load: true # Storing the image in docker is slow, so try and rely on caching
          file: docker/release_builder.Dockerfile
          target: flyline-builder
          # tags: "flyline-builder:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        # running the tests by building an image is a cache friendly way to do it
        # if we build a container, the previous step would need to have exported the image to docker
        # which is slow
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/release_builder.Dockerfile
          target: flyline-tests
          cache-from: type=gha
          # cache-to: type=gha,mode=max
