name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-ubuntu-1604:
    name: Build and test on Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dockerized 16.04 build
        run : ./docker/docker_build.sh

      - name: Run library tests inside Docker container
        run: docker run --rm flyline-builder bash -lc "cargo test --release --lib"
